# Generated by Django 5.2.3 on 2025-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='password',
            field=models.CharField(default='bad', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dummy',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
